
# tap repositories and their packages

tap homebrew/core
brew asdf
brew bash
brew ca-certificates
brew chezmoi
brew cloudflared
brew dav1d
brew direnv
brew ffmpeg
brew gettext
brew gh
brew git
brew go-task
brew googleworkspace-cli
brew icu4c@78
brew jq
brew json-c
brew krb5
brew lame
brew libpq
brew libunistring
brew libvmaf
brew libvpx
brew libyaml
brew lz4
brew mas
brew mpdecimal
brew mpg123
brew ncurses
brew oniguruma
brew openssl@3
brew opus
brew pcre2
brew postgresql@18
brew python@3.14
brew readline
brew ripgrep
brew sdl2
brew sdl3
brew sqlite
brew svt-av1
brew x264
brew x265
brew xz
brew zstd

tap homebrew/cask
cask 1password-cli
cask aws-vault
cask claude-code
cask cleanmymac-cli
cask codex
cask font-jetbrains-mono-nerd-font
cask gcloud-cli
cask ghostty
cask homebrew-app

tap 1password/tap

tap abue-ammar/tinycast
cask tinycast

tap aws/tap

tap dotenvx/brew

tap ducksss/tap
brew codex-profile --HEAD

tap getsentry/tools
brew sentry-cli

tap go-task/tap
cask go-task

tap hashicorp/tap

tap koekeishiya/formulae

tap macpaw/taps

tap rcmdnk/file
brew brew-file

tap stripe/stripe-cli

# App Store applications
appstore 1569813296 1Password for Safari (8.12.37)
appstore 302584613 Amazon Kindle (7.67)
appstore 1055511498 Day One (2026.19)
appstore 1452453066 Hidden Bar (1.8)
appstore 539883307 LINE (26.4.2)
appstore 1558360383 Menu Bar Calendar (1.7.2)
appstore 361304891 Numbers Creator Studio (15.3.1)
appstore 545519333 Prime Video (10.148)
appstore 803453959 Slack (4.52.162)
appstore 497799835 Xcode (27.0)
appstore 457622435 Yoink (3.7.6)
