
# tap repositories and their packages

tap homebrew/core
brew act --HEAD
brew aom
brew aribb24
brew asdf
brew autoconf
brew automake
brew brotli
brew ca-certificates
brew cairo
brew chezmoi
brew cjson
brew cmake
brew coreutils
brew curl
brew dav1d
brew ffmpeg
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew gawk
brew gcc
brew gdbm
brew gettext
brew gh
brew giflib
brew git
brew glib
brew gmp
brew gnupg
brew gnutls
brew go
brew go-task
brew goenv
brew graphite2
brew harfbuzz
brew highway
brew icu4c@75
brew icu4c@76
brew imath
brew isl
brew jpeg-turbo
brew jpeg-xl
brew jq
brew krb5
brew lame
brew leptonica
brew libarchive
brew libass
brew libassuan
brew libb2
brew libbluray
brew libdeflate
brew libevent
brew libgcrypt
brew libgpg-error
brew libidn2
brew libksba
brew libmicrohttpd
brew libmpc
brew libnghttp2
brew libogg
brew libpng
brew libpq
brew librist
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libusb
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew lz4
brew lzo
brew m4
brew mas
brew mbedtls
brew mercurial
brew mpdecimal
brew mpfr
brew mpg123
brew nettle
brew npth
brew nvm
brew oniguruma
brew opencore-amr
brew openexr
brew openjpeg
brew openssl@3
brew opus
brew p11-kit
brew pango
brew pcre2
brew pinentry
brew pixman
brew postgresql@14
brew python-packaging
brew python@3.10
brew python@3.11
brew python@3.13
brew rage
brew rav1e
brew readline
brew rtmpdump
brew rubberband
brew rustup
brew sdl2
brew snappy
brew speex
brew sqlite
brew srt
brew starship
brew svt-av1
brew tesseract
brew theora
brew tree
brew unbound
brew unixodbc
brew webp
brew x264
brew x265
brew xorgproto
brew xvid
brew xz
brew zeromq
brew zimg
brew zsh-syntax-highlighting
brew zstd

tap homebrew/cask
cask 1password-cli
cask aws-vault
cask battery
cask font-jetbrains-mono-nerd-font
cask warp

tap homebrew/bundle

tap homebrew/services

tap 1password/tap

tap aws/tap

tap go-task/tap

tap koekeishiya/formulae

tap rcmdnk/file
brew brew-file

tap stripe/stripe-cli
brew stripe

# App Store applications
appstore 1569813296 1Password for Safari (8.10.58)
appstore 1444383602 Goodnotes (6.6.4)
appstore 1452453066 Hidden Bar (1.8)
appstore 405399194 Kindle (1.40.3)
appstore 539883307 LINE (9.5.0)
appstore 1614666244 Mattermost (5.10.2)
appstore 409203825 Numbers (14.3)
appstore 545519333 Prime Video (10.59)
appstore 803453959 Slack (4.42.115)
appstore 497799835 Xcode (16.2)
appstore 457622435 Yoink (3.6.98)
